apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolset
  namespace: devsecops
  labels:
    app: toolset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolset
  template:
    metadata:
      labels:
        app: toolset
    spec:
      containers:
        - name: toolset
          image: docker.io/gulzada312/devsecops-mixed:latest
          imagePullPolicy: Always
          command: ["/usr/bin/tini","--"]
          args: ["bash","-lc","/home/appuser/py3/bin/python -m http.server 8080"]
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always