name: ci

on:
  push:
    branches: [ main, feature/** ]
    paths:
      - 'docker/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docker/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ---------- Build & Push Image ----------
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push image
        run: |
          DOCKER_BUILDKIT=1 docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/devsecops-mixed:latest \
            -f docker/Dockerfile docker
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devsecops-mixed:latest

      # ---------- Security Scan ----------
      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ hashFiles('docker/Dockerfile') }}
          restore-keys: |
            trivy-db-${{ runner.os }}-

      - name: Trivy scan (non-blocking; writes report file)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/devsecops-mixed:latest
          format: table
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          exit-code: '0'
          output: trivy-image.txt

      - name: Upload Trivy report artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image
          path: trivy-image.txt

      - name: Append Trivy report to artifacts/cve-report.md (main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          mkdir -p artifacts
          {
            echo "## $(date -u +'%Y-%m-%dT%H:%MZ') Trivy CI Scan"
            echo
            echo '```'
            cat trivy-image.txt
            echo '```'
            echo
          } >> artifacts/cve-report.md

      - name: Commit CVE report to repo (main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add artifacts/cve-report.md
          git commit -m "ci: append Trivy scan report [skip ci]" || echo "No changes to commit"
          git push || true